[package]
name = "group_files_into_dirs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.13", features = ["derive"] }
owo-colors = "4.0.0"
promkit = "0.4.5"
ratatui = "0.28.0"
regex = "1.10.6"
thiserror = "1.0.63"
unicode-normalization = "0.1.23"
